version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blanger-arte-rustica-api
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/health",
        ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
